#!/usr/bin/env sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [[ "$STAGED_FILES" = "" ]]; then
    exit 0
fi

./vendor/bin/pint $STAGED_FILES -q --preset laravel

git add $STAGED_FILES
